name: Azure Container Deploy

permissions:
  contents: read  
  
on:
  workflow_dispatch:

jobs: 
  init:
    name: CI Workflow
    uses: codeparce/ci-workflows/.github/workflows/node-init.yml@container-app
    secrets: inherit